name: 'Node Test'

on: [push]

jobs:
  build:
    name: 'Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node/

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Setup Node'
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 'Restore dependencies'
      run: npm ci

    - name: 'Run tests'
      run: npm test
